<Schema><DatabaseName>C:/Users/Валерия/Documents/диплом_м/нирм/URZ/OED_test1.mdb<Symbol><Type>Action
<Name>относится
<PosX>-100
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон2
<ContactPosType>Left
<ContactPosValue>0,4
<Contact><ContactName>Кон3
<ContactPosType>Top
<ContactPosValue>0,5
<Contact><ContactName>Что
<ContactPosType>Top
<ContactPosValue>0,2
<Symbol><Type>Relation
<Name>к
<PosX>-200
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чему
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>области
<PosX>-300
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон1
<ContactPosType>Right
<ContactPosValue>0,3
<Symbol><Type>Subject
<Name>электротехники
<PosX>-400
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Symbol><Type>Relation
<Name>и
<PosX>-500
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чему
<ContactPosType>Top
<ContactPosValue>0,6
<Symbol><Type>Relation
<Name>в
<PosX>-700
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чём
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>электронасосах
<PosX>-800
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон2
<ContactPosType>Left
<ContactPosValue>0,4
<Symbol><Type>Relation
<Name>с
<PosX>-900
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чем
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>двигателем
<PosX>-1000
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Symbol><Type>Relation
<Name>на
<PosX>-1100
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чём
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>магнитах
<PosX>-1200
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св11
<PropertyValue>постоянный
<PropertyHeight>10
<Symbol><Type>Action
<Name>быть
<PosX>-1400
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Symbol><Type>Action
<Name>может
<PosX>-1500
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Symbol><Type>Subject
<Name>Изобретение
<PosX>-1600
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>1
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>1
<SecondSymbolIndex>2
<FirstSymbolContact>Чему
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>2
<SecondSymbolIndex>3
<FirstSymbolContact>Кон1
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,3
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>4
<FirstSymbolContact>Кон3
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,5
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>4
<SecondSymbolIndex>4
<FirstSymbolContact>Чему
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,6
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>4
<SecondSymbolIndex>5
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>5
<SecondSymbolIndex>6
<FirstSymbolContact>Чём
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>6
<SecondSymbolIndex>7
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>7
<SecondSymbolIndex>8
<FirstSymbolContact>Чем
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>7
<SecondSymbolIndex>9
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>9
<SecondSymbolIndex>10
<FirstSymbolContact>Чём
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>9
<SecondSymbolIndex>11
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>9
<SecondSymbolIndex>12
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>13
<FirstSymbolContact>Что
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,2
</Schema>
