<Schema><DatabaseName>C:/Users/Валерия/Documents/диплом_м/нирм/URZ/OED_test1.mdb<Symbol><Type>Action
<Name>заключается
<PosX>-100
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон2
<ContactPosType>Left
<ContactPosValue>0,4
<Contact><ContactName>Кон2
<ContactPosType>Left
<ContactPosValue>0,4
<Contact><ContactName>Что
<ContactPosType>Top
<ContactPosValue>0,2
<Symbol><Type>Relation
<Name>в
<PosX>-200
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чём
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>повышении
<PosX>-300
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон1
<ContactPosType>Right
<ContactPosValue>0,3
<Contact><ContactName>Кон2
<ContactPosType>Left
<ContactPosValue>0,4
<Symbol><Type>Subject
<Name>жесткости
<PosX>-400
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Кон1
<ContactPosType>Right
<ContactPosValue>0,3
<Symbol><Type>Subject
<Name>вала
<PosX>-500
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св4
<PropertyValue>неподвижный
<PropertyHeight>10
<Contact><ContactName>Кон1
<ContactPosType>Right
<ContactPosValue>0,3
<Symbol><Type>Subject
<Name>электронасоса
<PosX>-700
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св6
<PropertyValue>экранированный
<PropertyHeight>10
<Symbol><Type>Relation
<Name>с
<PosX>-900
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чем
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>двигателем
<PosX>-1000
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Symbol><Type>Relation
<Name>на
<PosX>-1100
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Чём
<ContactPosType>Top
<ContactPosValue>0,1
<Symbol><Type>Subject
<Name>магнитах
<PosX>-1200
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св11
<PropertyValue>постоянный
<PropertyHeight>10
<Symbol><Type>Subject
<Name>результат
<PosX>-1400
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св13
<PropertyValue>технический
<PropertyHeight>10
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>1
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>1
<SecondSymbolIndex>2
<FirstSymbolContact>Чём
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>2
<SecondSymbolIndex>3
<FirstSymbolContact>Кон1
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,3
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>3
<SecondSymbolIndex>4
<FirstSymbolContact>Кон1
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,3
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>4
<SecondSymbolIndex>5
<FirstSymbolContact>Кон1
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,3
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>2
<SecondSymbolIndex>6
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>6
<SecondSymbolIndex>7
<FirstSymbolContact>Чем
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>8
<FirstSymbolContact>Кон2
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,4
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>8
<SecondSymbolIndex>9
<FirstSymbolContact>Чём
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>10
<FirstSymbolContact>Что
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,2
</Schema>
