<Schema><DatabaseName>C:/Users/Валерия/Documents/диплом_м/нирм/URZ/OED_test1.mdb<Symbol><Type>Action
<Name>увидел
<PosX>-100
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Contact><ContactName>Что
<ContactPosType>Top
<ContactPosValue>0,1
<Contact><ContactName>Что
<ContactPosType>Top
<ContactPosValue>0,2
<Symbol><Type>Subject
<Name>яблоко
<PosX>-200
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query><ConditionItems></ConditionItems><TotalVerity>Positive
<Property>
<PropertyName>св1
<PropertyValue>красный
<PropertyHeight>10
<Symbol><Type>Subject
<Name>Я
<PosX>-400
<PosY>20
<Width>150
<Height>50
<PropertiesVisualization>NameValue
<BackgroundColor>16777215
<VertLinePosX>45
<Query>
<ConditionItems></ConditionItems><TotalVerity>Positive
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>1
<FirstSymbolContact>Что
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,1
<Connection>
<ConnectionType>Straight
<FirstSymbolIndex>0
<SecondSymbolIndex>2
<FirstSymbolContact>Что
<SecondSymbolContactPosType>Top
<SecondSymbolContactPosValue>0,2
</Schema>
